import type { NextPage } from 'next'
import Head from 'next/head'

import Clients from '../components/Clients'
import Container from '../components/Container'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pinapple Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className={styles.main}>
        <Container>
          <Hero />
          <Clients/>
        </Container>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
